name: Terraform Plan & Apply

on:
  push:
    branches:
      - main # or the name of your default branch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: cd terraform-digitalocean-k8s && terraform init

    - name: Terraform Plan
      run: cd terraform-digitalocean-k8s && terraform plan -var="do_token=${{ secrets.DO_ACCESS_TOKEN }}" -out=tfplan && cat tfplan

    #- name: Terraform Apply
    #  run: terraform apply -var="do_token=${{ secrets.DO_ACCESS_TOKEN }}" -auto-approve
